# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"help_stack": "00_help_stack.ipynb",
         "api": "00_help_stack.ipynb"}

modules = ["help_stack.py"]

doc_url = "https://pages.github.walmart.com/pages/n0r033u/helpstack/"

git_url = "https://gecgithub01.walmart.com/n0r033u/helpstack/tree/master/"

def custom_doc_links(name): return None
